import type { Locale } from '@/lib/i18n';

/**
 * 界面文案。新增语言时在此处补齐一套键值即可，缺失会在类型检查阶段报错。
 */
const zh = {
    site: {
      name: 'Anahgo Lab',
      tagline: '在爱的火花中寻找平和，伟大来源于微小的实践',
      description:
        'Anahgo Lab 收录并维护一批独立的在线工具与文档站：协议报文解析、命令速查、配置指南、云服务商导航等。按用途检索，直接进入对应站点。',
    },
    nav: {
      about: '关于',
      index: '索引',
      language: '语言',
      theme: '主题',
      themeLight: '浅色',
      themeDark: '深色',
      themeSystem: '跟随系统',
      skipToContent: '跳到主要内容',
    },
    home: {
      heading: '三十辐，共一毂。',
      lede: '毂因其空，方受三十辐。此间不留一物，才放得下所有去处。（《道德经》十一章）',
      browseProjects: '查看全部项目',
      domainStripLabel: '全部项目',
      statsProjects: '已上线项目',
      statsCategories: '分类',
      statsUpdated: '最近更新',
      featuredTitle: '重点推荐',
      allTitle: '全部项目',
      searchPlaceholder: '搜索项目、域名或标签',
      searchLabel: '项目搜索',
      filterAll: '全部',
      layoutLabel: '布局',
      layoutGrid: '宫格',
      layoutList: '列表',
      layoutCompact: '紧凑',
      sortLabel: '排序',
      sortUpdated: '最近更新',
      sortName: '名称',
      emptyTitle: '没有匹配的项目',
      emptyBody: '换个关键词，或清空筛选条件再看。',
      clearFilters: '清除筛选',
      resultCount: '共 {count} 个项目',
      openSite: '打开站点',
      readMore: '查看详情',
      viewProject: '项目说明',
    },
    project: {
      overview: '项目概述',
      highlights: '主要能力',
      details: '项目信息',
      domain: '域名',
      category: '分类',
      status: '状态',
      updated: '最近更新',
      released: '首次上线',
      tagsLabel: '技术标签',
      visit: '访问站点',
      related: '相关项目',
      backToIndex: '返回索引',
      notFoundTitle: '没有这个项目',
      notFoundBody: '地址可能已经变更。回到索引页看看其它项目。',
    },
    status: {
      live: '在线',
      beta: '测试中',
      maintenance: '维护中',
    },
    category: {
      tool: '在线工具',
      reference: '速查参考',
      guide: '配置指南',
      directory: '站点导航',
    },
    breadcrumb: {
      home: '索引',
    },
    about: {
      eyebrow: '缘起',
      heading: '散出去的，总得有处可回。',
      /** 标题与面包屑专用：正文标题是意象句，不含检索词 */
      seoTitle: '关于这个索引站',
      body: '域名各自成家，门牌越挂越远。这里没有可用的东西，只有一张写去向的表：谁在哪里，如今什么光景。',
      principleTitle: '什么会被收进来',
      principles: [
        '有自己的域名，能单独打开。',
        '只解决一个具体问题。',
        '打开即可用，不必注册，也不带走数据。',
      ],
      contactTitle: '联系与反馈',
      contactBody: '哪里坏了，或者还缺什么，从各站内的反馈入口说一声就行。',
    },
    footer: {
      rights: '保留所有权利',
      sections: '栏目',
      projects: '项目',
      legal: '说明',
    },
    console: {
      title: '管理入口',
      lockedTitle: '需要通行码',
      lockedBody: '输入通行码以进入管理界面。',
      passphraseLabel: '通行码',
      unlock: '进入',
      cancel: '取消',
      wrongPassphrase: '通行码不正确',
      hint: '后端与数据库尚未接入，界面为占位状态。',
      panelTitle: '管理面板',
      panelBody: '项目增删改、排序与多语言文案维护将在接入后端后开放。',
      secretHint: '入口不在导航与站点地图中显示。',
      hidden: '已撤下',
    },
    notFound: {
      title: '页面不存在',
      body: '这个地址没有对应内容。',
      backHome: '回到首页',
    },
};

type Dictionary = typeof zh;

const en: Dictionary = {
    site: {
      name: 'Anahgo Lab',
      tagline: 'Find peace in the sparks of love; greatness comes from small practice.',
      description:
        'Anahgo Lab catalogs a set of standalone online tools and documentation sites: protocol packet parsing, command references, setup guides, cloud provider directories and more. Browse by purpose and jump straight to the site.',
    },
    nav: {
      about: 'About',
      index: 'Index',
      language: 'Language',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeSystem: 'System',
      skipToContent: 'Skip to main content',
    },
    home: {
      heading: 'Thirty spokes share one hub.',
      lede: 'The hub holds the spokes because it is hollow. Nothing is kept here, so there is room for every destination. (Laozi, Tao Te Ching 11)',
      browseProjects: 'Browse all projects',
      domainStripLabel: 'All projects',
      statsProjects: 'Live projects',
      statsCategories: 'Categories',
      statsUpdated: 'Last updated',
      featuredTitle: 'Featured',
      allTitle: 'All projects',
      searchPlaceholder: 'Search projects, domains or tags',
      searchLabel: 'Project search',
      filterAll: 'All',
      layoutLabel: 'Layout',
      layoutGrid: 'Grid',
      layoutList: 'List',
      layoutCompact: 'Compact',
      sortLabel: 'Sort',
      sortUpdated: 'Recently updated',
      sortName: 'Name',
      emptyTitle: 'No matching projects',
      emptyBody: 'Try another keyword, or clear the filters.',
      clearFilters: 'Clear filters',
      resultCount: '{count} projects',
      openSite: 'Open site',
      readMore: 'Details',
      viewProject: 'Project notes',
    },
    project: {
      overview: 'Overview',
      highlights: 'What it does',
      details: 'Details',
      domain: 'Domain',
      category: 'Category',
      status: 'Status',
      updated: 'Last updated',
      released: 'First released',
      tagsLabel: 'Tags',
      visit: 'Visit site',
      related: 'Related',
      backToIndex: 'Back to index',
      notFoundTitle: 'No such project',
      notFoundBody: 'The address may have changed. Head back to the index for everything else.',
    },
    status: {
      live: 'Live',
      beta: 'Beta',
      maintenance: 'Maintenance',
    },
    category: {
      tool: 'Tools',
      reference: 'References',
      guide: 'Guides',
      directory: 'Directories',
    },
    breadcrumb: {
      home: 'Index',
    },
    about: {
      eyebrow: 'Origin',
      heading: 'What scatters needs somewhere to come back to.',
      seoTitle: 'About this index',
      body: 'Each domain keeps its own house, and the signboards drift further out. Nothing here is usable. Just a table of where things went: who is where, and what shape they are in now.',
      principleTitle: 'What makes it here',
      principles: [
        'Its own domain, and it opens on its own.',
        'One specific problem, and nothing beyond it.',
        'Opens and works. No account, and nothing leaves your side.',
      ],
      contactTitle: 'Contact and feedback',
      contactBody: 'Something broken, or something missing? The feedback link inside each site reaches us.',
    },
    footer: {
      rights: 'All rights reserved',
      sections: 'Sections',
      projects: 'Projects',
      legal: 'Notes',
    },
    console: {
      title: 'Admin',
      lockedTitle: 'Passphrase required',
      lockedBody: 'Enter the passphrase to open the admin area.',
      passphraseLabel: 'Passphrase',
      unlock: 'Enter',
      cancel: 'Cancel',
      wrongPassphrase: 'Passphrase not accepted',
      hint: 'Backend and database are not connected yet. This screen is a placeholder.',
      panelTitle: 'Admin panel',
      panelBody: 'Creating, editing, reordering and translating projects opens up once the backend is connected.',
      secretHint: 'This entry is absent from navigation and sitemap.',
      hidden: 'Withdrawn',
    },
    notFound: {
      title: 'Page not found',
      body: 'Nothing lives at this address.',
      backHome: 'Back to home',
    },
};

const ja: Dictionary = {
    site: {
      name: 'Anahgo Lab',
      tagline: '愛の火花に平和を見いだし、偉大さは小さな実践から生まれる。',
      description:
        'Anahgo Lab は独立したオンラインツールとドキュメントサイトをまとめた索引です。プロトコル解析、コマンド早見表、設定ガイド、クラウド事業者のディレクトリなどを用途から探せます。',
    },
    nav: {
      about: '概要',
      index: '索引',
      language: '言語',
      theme: 'テーマ',
      themeLight: 'ライト',
      themeDark: 'ダーク',
      themeSystem: 'システム',
      skipToContent: '本文へ移動',
    },
    home: {
      heading: '三十輻、一轂を共にす。',
      lede: '轂は空なるがゆえに輻を受ける。ここには何も置かない。だからこそ、あらゆる行き先が収まる。（『老子』十一章）',
      browseProjects: 'すべてのプロジェクト',
      domainStripLabel: '全プロジェクト',
      statsProjects: '公開中',
      statsCategories: '分類',
      statsUpdated: '最終更新',
      featuredTitle: '注目',
      allTitle: 'すべて',
      searchPlaceholder: 'プロジェクト・ドメイン・タグを検索',
      searchLabel: 'プロジェクト検索',
      filterAll: 'すべて',
      layoutLabel: 'レイアウト',
      layoutGrid: 'グリッド',
      layoutList: 'リスト',
      layoutCompact: 'コンパクト',
      sortLabel: '並び替え',
      sortUpdated: '更新日',
      sortName: '名前',
      emptyTitle: '該当するプロジェクトがありません',
      emptyBody: '別のキーワードを試すか、絞り込みを解除してください。',
      clearFilters: '絞り込みを解除',
      resultCount: '{count} 件',
      openSite: 'サイトを開く',
      readMore: '詳細',
      viewProject: '説明を見る',
    },
    project: {
      overview: '概要',
      highlights: '主な機能',
      details: '詳細情報',
      domain: 'ドメイン',
      category: '分類',
      status: '状態',
      updated: '最終更新',
      released: '公開日',
      tagsLabel: 'タグ',
      visit: 'サイトを開く',
      related: '関連プロジェクト',
      backToIndex: '索引に戻る',
      notFoundTitle: 'プロジェクトが見つかりません',
      notFoundBody: 'URL が変わっている可能性があります。索引から他を探してください。',
    },
    status: {
      live: '公開中',
      beta: 'ベータ',
      maintenance: 'メンテナンス',
    },
    category: {
      tool: 'ツール',
      reference: 'リファレンス',
      guide: 'ガイド',
      directory: 'ディレクトリ',
    },
    breadcrumb: {
      home: '索引',
    },
    about: {
      eyebrow: '由来',
      heading: '散ったものに、戻る場所を。',
      seoTitle: 'この索引について',
      body: 'ドメインはそれぞれに家を構え、看板は遠ざかっていく。ここに使えるものはない。あるのは行き先を記した一覧だけ。誰がどこにいて、いまどんな具合か。',
      principleTitle: 'ここに載るもの',
      principles: ['自分のドメインを持ち、単体で開く。', '特定の問題をひとつだけ解く。', '開けば使える。登録も、データの外出もない。'],
      contactTitle: '連絡とフィードバック',
      contactBody: '壊れているところ、足りないものがあれば、各サイト内のフィードバック入口から知らせてほしい。',
    },
    footer: {
      rights: 'All rights reserved',
      sections: 'セクション',
      projects: 'プロジェクト',
      legal: '注記',
    },
    console: {
      title: '管理',
      lockedTitle: 'パスフレーズが必要です',
      lockedBody: 'パスフレーズを入力して管理画面を開きます。',
      passphraseLabel: 'パスフレーズ',
      unlock: '入る',
      cancel: 'キャンセル',
      wrongPassphrase: 'パスフレーズが正しくありません',
      hint: 'バックエンドとデータベースは未接続です。この画面は仮の状態です。',
      panelTitle: '管理パネル',
      panelBody: 'プロジェクトの追加・編集・並び替え・翻訳管理は、バックエンド接続後に開放されます。',
      secretHint: 'この入口はナビゲーションとサイトマップには表示されません。',
      hidden: '非公開',
    },
    notFound: {
      title: 'ページが見つかりません',
      body: 'このアドレスに内容はありません。',
      backHome: 'ホームへ戻る',
    },
};

export type { Dictionary };

export const dictionary: Record<Locale, Dictionary> = { zh, en, ja };

export function getDictionary(locale: Locale): Dictionary {
  return dictionary[locale];
}

/** 把 {count} 之类的占位替换为实际数值 */
export function format(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
